# ???????????? API
api.nominatim.url=https://nominatim.openstreetmap.org/search
api.user.agent=LandPlotAnalyzer/1.0 (Scientific Research)

# ????????? ????, ???? ???????? ?????? ??????
currency.default.rate=41.5
# ????????? URL ??? (??? ???? ???????)
api.nbu.url=https://bank.gov.ua/NBUStatService/v1/statistichny/exchange?valcode=USD&json

# ???????????? ????? ????????
app.title=Land Plot Analyzer
app.fxml.main=/fxml/main_view.fxml

# ???????? ???????????? ????? (?????????? ??????)
map.default.lat=49.8397
map.default.lon=24.0297
map.default.zoom=12

# ???????????? ???????????? ??????? (???????)
plot.color.border=#c0392b
plot.color.fill=#e74c3c
plot.opacity=0.4

# Test coordinates
cadastr.number  = 4610136900:01:001:0001
location = ?????????????, ?????
zubra = 49.7792, 24.0452; 49.7794, 24.0454; 49.7793, 24.0458; 49.7790, 24.0456.