app.title=Land Plot Analyzer
app.fxml.main=/fxml/main_view.fxml
map.default.lat=49.8397
map.default.lon=24.0297
map.default.zoom=12

#Testing Data
cadastr.number.example = 4610136900:01:001:0001
location.example = ?????????????, ?????
coordinates.example = 49.7792, 24.0452; 49.7794, 24.0454; 49.7793, 24.0458; 49.7790, 24.0456

#PDF Style
pdf.font.path=C:/Windows/Fonts/arial.ttf
pdf.color.main=#2C3E50
pdf.color.accent=#27AE60
pdf.color.background=#F5F7F9

#Report Coordinator
report.layer.switch.delay.ms=2000
report.final.exit.delay.ms=3000

#Text Constants
pdf.report.header=LAND PLOT ANALYZER | PhD RESEARCH MODULE

#AI Generation Enabler
analysis.ai.enabled=false

#Gemini AI
ai.gemini.model=gemini-3-flash-preview
ai.gemini.sentence.limit=5
ai.gemini.language=???????????

#Elevation API Service Configuration
api.elevation.url=https://api.open-elevation.com/api/v1/lookup?locations=
api.elevation.default=250.0

#Cadastre Api Service Configuration
api.cadastre.mock.data.path=/cadastre_data.json
api.cadastre.url.template=https://e.land.gov.ua/api/v1/cadastre/

#Exchange Rate Service Configuration
api.exchange.privat.url=https://api.privatbank.ua/p24api/pubinfo?exchange&coursid=5
api.exchange.nbu.url=https://bank.gov.ua/NBUStatService/v1/statistichny/exchange?valcode=USD&json
currency.default.rate=42.5

#Geo Api Service Configuration
api.nominatim.url=https://nominatim.openstreetmap.org/search
api.user.agent=LandPlotAnalyzer/1.0 (Scientific Research)
api.nominatim.format=json
api.nominatim.limit=1
api.nominatim.polygon=1

# Open-Meteo API (Climate Data)
api.weather.url=https://archive-api.open-meteo.com/v1/archive
api.weather.params=&daily=temperature_2m_max,temperature_2m_min,precipitation_sum&timezone=auto

#File Util Configuration
reports.directory=Reports
reports.file.prefix=Zvit_
reports.date.format=yyyy-MM-dd_HH-mm-ss

# GEO Consts
geo.earth.radius=6371000.0
geo.meters.per.degree=111319.9